### PR TITLE
Add ability to retrieve relative file with hostname of name of '.' , add open_raw function to make FileAdapter extendable and more flexible

### PR DESCRIPTION
**Pull request by huakim**

### CODE REVIEW

**Comment by dashea** [comment]
Can you explain what it is you’re ultimately trying to do with these changes? I don’t understand what the use case is that you’re aiming to solve.

**Comment by huakim** [comment]
Now the content of all files being merged is not loaded into memory before being returned

**Comment by dashea** [comment]
This is turning into a lot of code, and you still haven't answered what it's all for. What is your use case for accessing a collection of files via extensions to a file URI, and accessing it as all one file? How does going through the requests library benefit you over accessing the files directly via `glob` or something similar?

**Comment by huakim** [comment]
> This is turning into a lot of code, and you still haven't answered what it's all for. What is your use case for accessing a collection of files via extensions to a file URI, and accessing it as all one file? How does going through the requests library benefit you over accessing the files directly via `glob` or something similar?
Library benefits a lot, if i have access to glob function, for example, i can read content of the file without knowing actually path of file, but piece of. Of course, FileAdapter must also have an option to disable glob functionality

**Comment by huakim** [comment]
> This is turning into a lot of code, and you still haven't answered what it's all for. What is your use case for accessing a collection of files via extensions to a file URI, and accessing it as all one file? How does going through the requests library benefit you over accessing the files directly via `glob` or something similar?

Library benefits a lot, if i have access to glob function, for example, i can read content of the file without knowing actually path of file, but piece of. Of course, FileAdapter must also have an option to disable glob functionality

**Comment by huakim** [comment]
> This is turning into a lot of code, and you still haven't answered what it's all for. What is your use case for accessing a collection of files via extensions to a file URI, and accessing it as all one file? How does going through the requests library benefit you over accessing the files directly via `glob` or something similar?

Okay, understand, but I still need to modify some parts of source code to order to create GlobAdapter on top of it (GlobAdapter will be inherited from FileAdapter)

**Pull request closed without merging**
